name: Hello CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Give permission to execute Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build


      - name: 🔍 SonarCloud Analysis
        run: ./gradlew clean build sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}